### ISSUE TITLE
Give #toggleContainer some margin to make it easier to click

### ISSUE THREAD

**Issue by AndreasGalster** [PolymerElements/paper-toggle-button#31]
Clicking the toggle button is quite hard, especially when you don't click on the #toggleButton and instead on the #toggleBar. Something like margin:5px on #toggleContainer seems about right in my opinion.

Actually I'm just wondering. I've never really used github for committing stuff etc. and I'm not sure how committing for a project like this works. Is it possible for other non-google people to commit recommendations to those projects?

**Comment by notwaldorf** [comment]
I can't reproduce this -- clicking on the toggle-bar flips the button as well. Since this is an old issue -- is this still reproducible?

Yes, it's absolutely possible (and appreciated, and encouraged! :balloon:) for non-googlers to commit fixes! You would just send a pull request when you're ready, and our CLA bot would ask you to one-time sign a CLA. 

However, I would like to be able to repro this and understand what the problem is before trying to fix it :)

**Comment by AndreasGalster** [comment]
Yes, I'm already beginning to commit :). The issue seems to be fixed with the latest version of the toggle-button. 

To understand the issue btw: You had to click exactly on the bar to toggle the button. As lazy people we sometimes tend to just click near (a few pixels off) the bar though.
