### ISSUE TITLE
[A11y 8/27] "unlabeled 0 toggle button" JAWS verbalization

### ISSUE THREAD

**Issue by lpalmaro** [PolymerElements/paper-toggle-button#40]
On Windows with JAWS screen reader on Firefox and Chrome, I get the spoken feedback "unlabeled 0 toggle button" every time I access the toggles. Any idea why?

**Comment by dfreedm** [comment]
Hmm, in the demo it looks like JAWS is not smart enough to read the text content of the element to fill in the label.
In paper-radio-button, it looks like we generate the aria-label dynamically, perhaps because of this?
https://github.com/PolymerElements/paper-radio-button/blob/master/paper-radio-button.html#L97-L116

@notwaldorf
