### ISSUE TITLE
Should require paper-behaviors v1.0.5 or higher

### ISSUE THREAD

**Issue by jhpedemonte** [PolymerElements/paper-toggle-button#54]
This change on [Aug 25](https://github.com/PolymerElements/paper-toggle-button/commit/14e227400f2bf07abff938b0fbff9e32878f03e8) adds the use of `paper-checked-element-behavior`, which wasn't added to _paper-behaviors_ until v1.0.5. But _bower.json_ still has version as 1.0.0 or higher. Should be updated to at least v1.0.5.

Ran into this in one of my projects where _paper-behaviors_ was downloaded as 1.0.4. When _paper-toggle-button_ was updated to latest release, it stopped working because it couldn't find `paper-checked-element-behavior`.

**Comment by notwaldorf** [comment]
`paper-behaviours#^1.0.0` means "the latest version of paper-behaviors, up to 2.0.0", which means that when you update an element, you _need_ to update its dependencies as well. We can't target specific releases for dependencies, because the dependency graph is actually really messy. The best we can do is guarantee that if you update `paper-toggle-button`'s version _and_ update its dependencies, everything will work good together.
