### ISSUE TITLE
What is "value" meant to contain? Should it change when `checked` or `active` change?

### ISSUE THREAD

**Issue by mercmobily** [PolymerElements/paper-toggle-button#98]
What is "value" supposed to contain? At the moment, it seems to be always "on" regardless of "checked" or "active".
I am writing a widget that auto-populates a form; for paper-toggle-button elements, it's a boolean. At the moment, when I have a paper-toggle-button I am actually raising an exception and assigning `domElement.checked` rather than `domElement.value`, but...

What is it meant to contain? Should `value` change when `checked` or `active` change?

**Comment by mercmobily** [comment]
I looked at iron-form to see how it does it, and noticed that it uses `_usesCheckedInsteadOfValue` which reads like this:

```
_usesCheckedInsteadOfValue: function(el) {
    if (el.type == 'checkbox' ||
        el.type == 'radio' ||
        el.getAttribute('role') == 'checkbox' ||
        el.getAttribute('role') == 'radio' ||
        el['_hasIronCheckedElementBehavior']) {
      return true;
    }
    return false;
  },
```

By looking at how native checkboxes work too, this may indeed be the only way... ugh.

**Comment by bicknellr** [comment]
Yeah, that's pretty much what happened - value's weirdness is carried over from strange native checkbox behavior. The value property comes from [IronCheckedElementBehavior](https://github.com/PolymerElements/iron-checked-element-behavior) which tries to closely mirror the [HTML spec for checkbox inputs](https://html.spec.whatwg.org/#checkbox-state-%28type=checkbox%29). An input's value property uses one of a few 'modes' and checkboxes use a particularly weird mode called [default/on](https://html.spec.whatwg.org/#dom-input-value-default-on). In this mode, 'on' is returned when accessing the 'value' _property_ of the input if the 'value' _attribute_ is not set. Also, like you found, iron-form uses a similar method for building form data as [the method given in the HTML spec](https://html.spec.whatwg.org/#constructing-the-form-data-set), which excludes checkboxes and radio buttons based on their 'checkedness'.

(Closing since this isn't a bug but let me know if you've got follow-up questions.)

**Comment by mercmobily** [comment]
Not really a follow-up question, but something to think about...
The current behaviour of checkboxes is to send their "value" over when a form is submitted. 
For example if you have:

```
          <form method="POST" action="submit_validating">
            <input name="maker" id="maker" ></input>
            <input name="model" id="model"></input>
            <input type="checkbox" name="checker" value="SSS1">Check me</input>
            <input type="checkbox" name="checker" value="SSS2">Check me</input>
            <button type="submit">Submit!</button>
          </form>
```

You might end up with:

```
maker:dds
model:ad
checker:SSS1
checker:SSS2
```

Languages like PHP allow you to name an input `checker[]` for example, so that when you have a case like above, you end up with an array.

OK, PHP is ugly as war crime. OK, this makes it "interesting" if you are trying to submit JSON.
But, the main thing to remember (and maybe document) is that **while `<form>` will submit a checkbox's value, an `<iron-form>` will submit "true" or "false"**.

This is a major difference, and it must be kept into consideration when making forms. in `<paper-checkbox>`, the `value` element _really is useless_, whereas it did have a point in "normal" HTML forms.

If I am right, rather than leaving this rot in a hidden GitHub issue, we could:

1) Document this carefully OR
2) Change how `<iron-form>` submits, giving the option to emulate "native" behaviour of `<form>` in terms of checkboxes OR
3) (breaking change) Change how `<iron-form>` works, so that it emulates the way `<form>` works in terms of checkboxes.

Just my 2c... probably only worth 1c though!
